# Generated by Django 3.0.8 on 2020-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='Pod_Logo'),
        ),
    ]
