# Generated by Django 3.0.8 on 2020-08-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20200811_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='media/audio_file'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='logo',
            field=models.ImageField(default='media/default.jpg', upload_to='media/Pod_Logo'),
        ),
    ]
