# Generated by Django 3.0.8 on 2020-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20200811_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='audio_file'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='Pod_Logo'),
        ),
    ]
